### ISSUE TITLE
<delete this>

### ISSUE THREAD

**Issue by gek169** [thehugh100/Insipid3D#2]
How are you doing?
How's development?
How's the pandemic?
Got any way we can chat?

Love the project, I love that you're still working on it. I keep moving between projects.

**Comment by thehugh100** [comment]
Doing good thanks, how are you?

Got a fair amount working now development wise, just caught the spark for
the project again.

Sadly the pandemic caused me to loose my job hence why I have enough time
to work on it again

Add me on discord Hugh#0715

Cheers,

Hugh
